# Generated by Django 4.2.14 on 2024-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField(default=0, help_text='In minutes')),
                ('ingredients', models.CharField(help_text='Separate each ingredient by a comma', max_length=120)),
                ('description', models.TextField()),
            ],
        ),
    ]
