# Generated by Django 4.2.14 on 2024-08-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='recipe',
            name='_difficulty',
            field=models.CharField(default='', max_length=120),
        ),
    ]
